[theme]
primaryColor = "#2C3E50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "Poppins"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true

[client]
showErrorDetails = true

[global]
developmentMode = false

[ui]
hideTopBar = true
hideSidebarNav = false

[pages]
# Solo mostrar estas páginas en el sidebar
pages = [
    "pages/Inicio.py",
    "pages/Registro.py",
    "pages/Tu Super online.py"
]

# Ocultar el resto de las páginas
hidePages = [
    "pages/Buscador de productos.py",
    "pages/Forma de Pago.py",
    "pages/Pedido exitoso.py",
    "pages/Mi perfil.py"
]

[sidebar]
# Configuración del sidebar
collapsed = false 